-- Platform super-admin support for the server-rendered /admin panel, separate from a trip's
-- OWNER/EDITOR/VIEWER role. IS_SUPERADMIN gates the panel; ADMIN_AUDIT_LOG is an append-only
-- record of every admin mutation (who did what, to which target, when) for traceability.

-- Oracle has no native boolean: NUMBER(1) with a default so existing rows stay valid under NOT NULL.
ALTER TABLE USERS ADD (IS_SUPERADMIN NUMBER(1) DEFAULT 0 NOT NULL);

CREATE TABLE ADMIN_AUDIT_LOG (
    ID            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RID           VARCHAR2(36) NOT NULL,
    -- The admin who acted. Nullable so a deleted admin's history survives (FK cleared, row kept).
    ACTOR_USER_ID NUMBER(19),
    ACTION        VARCHAR2(60) NOT NULL,
    TARGET_TYPE   VARCHAR2(40),
    TARGET_RID    VARCHAR2(36),
    -- Free-form JSON detail (before/after, reason, …).
    DETAIL        CLOB,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT UK_ADMIN_AUDIT_LOG_RID UNIQUE (RID),
    CONSTRAINT FK_ADMIN_AUDIT_ACTOR FOREIGN KEY (ACTOR_USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IX_ADMIN_AUDIT_CREATED_AT ON ADMIN_AUDIT_LOG (CREATED_AT);
