-- V2 — Auth (M2): USERS, USER_DEVICES, AUTH_TOKENS (SPEC §6 Module 1, §5).
-- Oracle conventions (CLAUDE.md "Oracle gotchas"):
--   * ID is an identity column; RID is the public UUID v7 (UNIQUE per table).
--   * booleans/flags are NUMBER(1) (no native boolean).
--   * optional text columns are nullable and written as NULL, never '' (Oracle stores '' as NULL).
--   * business uniques are FUNCTION-BASED partial indexes that only apply WHEN IS_DELETED = 0.
--   * index every FK.

-- ─── USERS ────────────────────────────────────────────────────────────────────
CREATE TABLE USERS (
    ID               NUMBER(19)   GENERATED BY DEFAULT ON NULL AS IDENTITY,
    RID              VARCHAR2(36)  NOT NULL,
    EMAIL            VARCHAR2(255) NOT NULL,
    PASSWORD_HASH    VARCHAR2(255),                       -- NULL for Google-only accounts
    NAME             VARCHAR2(150) NOT NULL,
    AVATAR           VARCHAR2(500),
    TIMEZONE         VARCHAR2(64)  DEFAULT 'Asia/Ho_Chi_Minh' NOT NULL,
    DEFAULT_CURRENCY VARCHAR2(3)   DEFAULT 'VND' NOT NULL,
    EMAIL_VERIFIED   NUMBER(1)     DEFAULT 0 NOT NULL,
    PROVIDER         VARCHAR2(20)  NOT NULL,              -- LOCAL | GOOGLE
    CREATED_AT       TIMESTAMP,
    CREATED_BY       NUMBER(19),
    UPDATED_AT       TIMESTAMP,
    UPDATED_BY       NUMBER(19),
    VERSION          NUMBER(10)    DEFAULT 0 NOT NULL,
    IS_DELETED       NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX UK_USERS_RID ON USERS (RID);
-- Email is unique only among live rows, so a soft-deleted account frees its email.
CREATE UNIQUE INDEX UK_USERS_EMAIL ON USERS (CASE WHEN IS_DELETED = 0 THEN EMAIL END);

-- ─── USER_DEVICES (FCM push targets) ───────────────────────────────────────────
CREATE TABLE USER_DEVICES (
    ID            NUMBER(19)   GENERATED BY DEFAULT ON NULL AS IDENTITY,
    RID           VARCHAR2(36)  NOT NULL,
    USER_ID       NUMBER(19)   NOT NULL,
    FCM_TOKEN     VARCHAR2(500) NOT NULL,
    PLATFORM      VARCHAR2(20)  NOT NULL,                 -- ANDROID | IOS
    LAST_SEEN_AT  TIMESTAMP,
    CREATED_AT    TIMESTAMP,
    CREATED_BY    NUMBER(19),
    UPDATED_AT    TIMESTAMP,
    UPDATED_BY    NUMBER(19),
    VERSION       NUMBER(10)    DEFAULT 0 NOT NULL,
    IS_DELETED    NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_USER_DEVICES PRIMARY KEY (ID),
    CONSTRAINT FK_USER_DEVICES_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);
CREATE UNIQUE INDEX UK_USER_DEVICES_RID ON USER_DEVICES (RID);
CREATE INDEX IX_USER_DEVICES_USER ON USER_DEVICES (USER_ID);
CREATE UNIQUE INDEX UK_USER_DEVICES_FCM ON USER_DEVICES (CASE WHEN IS_DELETED = 0 THEN FCM_TOKEN END);

-- ─── AUTH_TOKENS (email-verify, password-reset, refresh) ───────────────────────
CREATE TABLE AUTH_TOKENS (
    ID          NUMBER(19)   GENERATED BY DEFAULT ON NULL AS IDENTITY,
    RID         VARCHAR2(36)  NOT NULL,
    USER_ID     NUMBER(19)   NOT NULL,
    TYPE        VARCHAR2(20)  NOT NULL,                   -- EMAIL_VERIFY | PASSWORD_RESET | REFRESH
    TOKEN       VARCHAR2(255) NOT NULL,                   -- SHA-256 hash of the opaque token, never the token itself
    EXPIRES_AT  TIMESTAMP    NOT NULL,
    USED_AT     TIMESTAMP,                                -- set when consumed/rotated; non-null = spent
    CREATED_AT  TIMESTAMP,
    CREATED_BY  NUMBER(19),
    UPDATED_AT  TIMESTAMP,
    UPDATED_BY  NUMBER(19),
    VERSION     NUMBER(10)    DEFAULT 0 NOT NULL,
    IS_DELETED  NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_AUTH_TOKENS PRIMARY KEY (ID),
    CONSTRAINT FK_AUTH_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);
CREATE UNIQUE INDEX UK_AUTH_TOKENS_RID ON AUTH_TOKENS (RID);
CREATE INDEX IX_AUTH_TOKENS_USER_TYPE ON AUTH_TOKENS (USER_ID, TYPE);
CREATE INDEX IX_AUTH_TOKENS_TOKEN ON AUTH_TOKENS (TOKEN);
