-- V7 — Notifications (M8): SCHEDULED_NOTIFICATIONS (SPEC §6 Module 14).
-- Rows are generated when a trip/event changes and drained by a @Scheduled job that sends FCM.
-- EVENT_ID (beyond the spec's overview table) anchors event-derived reminders so editing one event
-- can cancel + regenerate just its reminders.

CREATE TABLE SCHEDULED_NOTIFICATIONS (
    ID            NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    RID           VARCHAR2(36)  NOT NULL,
    TRIP_ID       NUMBER(19),                              -- target trip (recipients = its members)
    USER_ID       NUMBER(19),                              -- target a single user, if set
    EVENT_ID      NUMBER(19),                              -- source event for reminders (regen anchor)
    TYPE          VARCHAR2(40)  NOT NULL,                  -- NotificationType
    PAYLOAD       VARCHAR2(1000) NOT NULL,                 -- json: { title, body, deeplink }
    SCHEDULED_AT  TIMESTAMP     NOT NULL,
    SENT_AT       TIMESTAMP,
    STATUS        VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL, -- PENDING | SENT | FAILED | CANCELLED
    CREATED_AT    TIMESTAMP,
    CREATED_BY    NUMBER(19),
    UPDATED_AT    TIMESTAMP,
    UPDATED_BY    NUMBER(19),
    VERSION       NUMBER(10)    DEFAULT 0 NOT NULL,
    IS_DELETED    NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SCHEDULED_NOTIFICATIONS PRIMARY KEY (ID),
    CONSTRAINT FK_SCHED_NOTIF_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIPS (ID),
    CONSTRAINT FK_SCHED_NOTIF_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_SCHED_NOTIF_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENTS (ID)
);
CREATE UNIQUE INDEX UK_SCHED_NOTIF_RID ON SCHEDULED_NOTIFICATIONS (RID);
-- The dispatch job scans this every minute.
CREATE INDEX IX_SCHED_NOTIF_DUE ON SCHEDULED_NOTIFICATIONS (STATUS, SCHEDULED_AT);
CREATE INDEX IX_SCHED_NOTIF_TRIP ON SCHEDULED_NOTIFICATIONS (TRIP_ID);
CREATE INDEX IX_SCHED_NOTIF_EVENT ON SCHEDULED_NOTIFICATIONS (EVENT_ID);
