-- V9 — Tickets: per-member tickets/QR (a member shows their own ticket QR at the gate).
-- Unlike a transport/accommodation booking's single QR_DATA, a ticket is assigned to ONE member
-- (MEMBER_ID -> TRIP_MEMBERS.ID), so each member can pull up just their own QR string and the app
-- regenerates the QR client-side (SPEC §2.7 — store the string, never an image).

CREATE TABLE TICKETS (
    ID           NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    RID          VARCHAR2(36)  NOT NULL,
    TRIP_ID      NUMBER(19)    NOT NULL,
    MEMBER_ID    NUMBER(19)    NOT NULL,                     -- TRIP_MEMBERS.ID (whose ticket it is)
    TITLE        VARCHAR2(200) NOT NULL,
    TICKET_TYPE  VARCHAR2(20)  DEFAULT 'OTHER' NOT NULL,     -- TicketType
    QR_DATA      VARCHAR2(4000) NOT NULL,                    -- decoded ticket/QR string (SPEC §2.7)
    NOTE         VARCHAR2(2000),
    CREATED_AT   TIMESTAMP,
    CREATED_BY   NUMBER(19),
    UPDATED_AT   TIMESTAMP,
    UPDATED_BY   NUMBER(19),
    VERSION      NUMBER(10)    DEFAULT 0 NOT NULL,
    IS_DELETED   NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT PK_TICKETS PRIMARY KEY (ID),
    CONSTRAINT FK_TICKETS_TRIP FOREIGN KEY (TRIP_ID) REFERENCES TRIPS (ID),
    CONSTRAINT FK_TICKETS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES TRIP_MEMBERS (ID)
);
CREATE UNIQUE INDEX UK_TICKETS_RID ON TICKETS (RID);
CREATE INDEX IX_TICKETS_TRIP ON TICKETS (TRIP_ID);
CREATE INDEX IX_TICKETS_MEMBER ON TICKETS (MEMBER_ID);
